Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,11 +6,21 @@ on:
   # Triggers the workflow every 5 minutes
   schedule:
     - cron: "*/5 * * * *"
+  push:
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
+    
 jobs:
   # This workflow contains a single job called "cron"
   cron:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+  build:
+    name: Test and build
+    environment: snyk-npm
+    runs-on: ubuntu-latest
+    
     # Step to run the snyk api "import target" endpoint as part of the job
     steps:
     - name : Snyk API Import
@@ -25,3 +35,32 @@ jobs:
             "branch":"master"
           }
          }'
+    - uses: actions/checkout@v2
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+
+    - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+      run: |
+        npm install snyk -g
+        npm install snyk-to-html -g
+        snyk auth ${{vars.SNYK_TOKEN}}
+
+    - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
+      run: |
+        snyk monitor
+       # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
+
+    - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+      run: |
+        snyk code test || true
+    - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+      run: |
+        docker build . -t yourimage:tag
+        snyk container monitor yourimage:tag --file=Dockerfile
+    - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+      run: |
+        snyk iac test || true
+  
